- name: checking variables from files
  hosts: local host
  become: yes
  vars_files:
  - variables.yaml
  tasks:
  - name: variables
    ansible.builtin.debug:
      msg: "hi, i am learning {{course}}, duration is {{duration}}"

      
