- name: loops 
  hosts: localhost
  become: yes
  tasks:
  - name: loops for unstall and install
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'git', state: 'present'}
    - {name: 'nginx', state: absent}
